#pragma once

#include <combaseapi.h>
#include <wincodec.h>
#include <Windows.h>

#include "platform/windows/utils.cpp"

void debugWicPixelFormat(WICPixelFormatGUID wicPixelFormat) {
	if (wicPixelFormat == GUID_WICPixelFormatUndefined) LOG(L"GUID_WICPixelFormatUndefined")
	if (wicPixelFormat == GUID_WICPixelFormatDontCare) LOG(L"GUID_WICPixelFormatDontCare")
	if (wicPixelFormat == GUID_WICPixelFormat1bppIndexed) LOG(L"GUID_WICPixelFormat1bppIndexed")
	if (wicPixelFormat == GUID_WICPixelFormat2bppIndexed) LOG(L"GUID_WICPixelFormat2bppIndexed")
	if (wicPixelFormat == GUID_WICPixelFormat4bppIndexed) LOG(L"GUID_WICPixelFormat4bppIndexed")
	if (wicPixelFormat == GUID_WICPixelFormat8bppIndexed) LOG(L"GUID_WICPixelFormat8bppIndexed")
	if (wicPixelFormat == GUID_WICPixelFormatBlackWhite) LOG(L"GUID_WICPixelFormatBlackWhite")
	if (wicPixelFormat == GUID_WICPixelFormat2bppGray) LOG(L"GUID_WICPixelFormat2bppGray")
	if (wicPixelFormat == GUID_WICPixelFormat4bppGray) LOG(L"GUID_WICPixelFormat4bppGray")
	if (wicPixelFormat == GUID_WICPixelFormat8bppGray) LOG(L"GUID_WICPixelFormat8bppGray")
	if (wicPixelFormat == GUID_WICPixelFormat8bppAlpha) LOG(L"GUID_WICPixelFormat8bppAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat16bppBGR555) LOG(L"GUID_WICPixelFormat16bppBGR555")
	if (wicPixelFormat == GUID_WICPixelFormat16bppBGR565) LOG(L"GUID_WICPixelFormat16bppBGR565")
	if (wicPixelFormat == GUID_WICPixelFormat16bppBGRA5551) LOG(L"GUID_WICPixelFormat16bppBGRA5551")
	if (wicPixelFormat == GUID_WICPixelFormat16bppGray) LOG(L"GUID_WICPixelFormat16bppGray")
	if (wicPixelFormat == GUID_WICPixelFormat24bppBGR) LOG(L"GUID_WICPixelFormat24bppBGR")
	if (wicPixelFormat == GUID_WICPixelFormat24bppRGB) LOG(L"GUID_WICPixelFormat24bppRGB")
	if (wicPixelFormat == GUID_WICPixelFormat32bppBGR) LOG(L"GUID_WICPixelFormat32bppBGR")
	if (wicPixelFormat == GUID_WICPixelFormat32bppBGRA) LOG(L"GUID_WICPixelFormat32bppBGRA")
	if (wicPixelFormat == GUID_WICPixelFormat32bppPBGRA) LOG(L"GUID_WICPixelFormat32bppPBGRA")
	if (wicPixelFormat == GUID_WICPixelFormat32bppGrayFloat) LOG(L"GUID_WICPixelFormat32bppGrayFloat")
	if (wicPixelFormat == GUID_WICPixelFormat32bppRGB) LOG(L"GUID_WICPixelFormat32bppRGB")
	if (wicPixelFormat == GUID_WICPixelFormat32bppRGBA) LOG(L"GUID_WICPixelFormat32bppRGBA")
	if (wicPixelFormat == GUID_WICPixelFormat32bppPRGBA) LOG(L"GUID_WICPixelFormat32bppPRGBA")
	if (wicPixelFormat == GUID_WICPixelFormat48bppRGB) LOG(L"GUID_WICPixelFormat48bppRGB")
	if (wicPixelFormat == GUID_WICPixelFormat48bppBGR) LOG(L"GUID_WICPixelFormat48bppBGR")
	if (wicPixelFormat == GUID_WICPixelFormat64bppRGB) LOG(L"GUID_WICPixelFormat64bppRGB")
	if (wicPixelFormat == GUID_WICPixelFormat64bppRGBA) LOG(L"GUID_WICPixelFormat64bppRGBA")
	if (wicPixelFormat == GUID_WICPixelFormat64bppBGRA) LOG(L"GUID_WICPixelFormat64bppBGRA")
	if (wicPixelFormat == GUID_WICPixelFormat64bppPRGBA) LOG(L"GUID_WICPixelFormat64bppPRGBA")
	if (wicPixelFormat == GUID_WICPixelFormat64bppPBGRA) LOG(L"GUID_WICPixelFormat64bppPBGRA")
	if (wicPixelFormat == GUID_WICPixelFormat16bppGrayFixedPoint) LOG(L"GUID_WICPixelFormat16bppGrayFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat32bppBGR101010) LOG(L"GUID_WICPixelFormat32bppBGR101010")
	if (wicPixelFormat == GUID_WICPixelFormat48bppRGBFixedPoint) LOG(L"GUID_WICPixelFormat48bppRGBFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat48bppBGRFixedPoint) LOG(L"GUID_WICPixelFormat48bppBGRFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat96bppRGBFixedPoint) LOG(L"GUID_WICPixelFormat96bppRGBFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat96bppRGBFloat) LOG(L"GUID_WICPixelFormat96bppRGBFloat")
	if (wicPixelFormat == GUID_WICPixelFormat128bppRGBAFloat) LOG(L"GUID_WICPixelFormat128bppRGBAFloat")
	if (wicPixelFormat == GUID_WICPixelFormat128bppPRGBAFloat) LOG(L"GUID_WICPixelFormat128bppPRGBAFloat")
	if (wicPixelFormat == GUID_WICPixelFormat128bppRGBFloat) LOG(L"GUID_WICPixelFormat128bppRGBFloat")
	if (wicPixelFormat == GUID_WICPixelFormat32bppCMYK) LOG(L"GUID_WICPixelFormat32bppCMYK")
	if (wicPixelFormat == GUID_WICPixelFormat64bppRGBAFixedPoint) LOG(L"GUID_WICPixelFormat64bppRGBAFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat64bppBGRAFixedPoint) LOG(L"GUID_WICPixelFormat64bppBGRAFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat64bppRGBFixedPoint) LOG(L"GUID_WICPixelFormat64bppRGBFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat128bppRGBAFixedPoint) LOG(L"GUID_WICPixelFormat128bppRGBAFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat128bppRGBFixedPoint) LOG(L"GUID_WICPixelFormat128bppRGBFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat64bppRGBAHalf) LOG(L"GUID_WICPixelFormat64bppRGBAHalf")
	if (wicPixelFormat == GUID_WICPixelFormat64bppPRGBAHalf) LOG(L"GUID_WICPixelFormat64bppPRGBAHalf")
	if (wicPixelFormat == GUID_WICPixelFormat64bppRGBHalf) LOG(L"GUID_WICPixelFormat64bppRGBHalf")
	if (wicPixelFormat == GUID_WICPixelFormat48bppRGBHalf) LOG(L"GUID_WICPixelFormat48bppRGBHalf")
	if (wicPixelFormat == GUID_WICPixelFormat32bppRGBE) LOG(L"GUID_WICPixelFormat32bppRGBE")
	if (wicPixelFormat == GUID_WICPixelFormat16bppGrayHalf) LOG(L"GUID_WICPixelFormat16bppGrayHalf")
	if (wicPixelFormat == GUID_WICPixelFormat32bppGrayFixedPoint) LOG(L"GUID_WICPixelFormat32bppGrayFixedPoint")
	if (wicPixelFormat == GUID_WICPixelFormat32bppRGBA1010102) LOG(L"GUID_WICPixelFormat32bppRGBA1010102")
	if (wicPixelFormat == GUID_WICPixelFormat32bppRGBA1010102XR) LOG(L"GUID_WICPixelFormat32bppRGBA1010102XR")
	if (wicPixelFormat == GUID_WICPixelFormat32bppR10G10B10A2) LOG(L"GUID_WICPixelFormat32bppR10G10B10A2")
	if (wicPixelFormat == GUID_WICPixelFormat32bppR10G10B10A2HDR10) LOG(L"GUID_WICPixelFormat32bppR10G10B10A2HDR10")
	if (wicPixelFormat == GUID_WICPixelFormat64bppCMYK) LOG(L"GUID_WICPixelFormat64bppCMYK")
	if (wicPixelFormat == GUID_WICPixelFormat24bpp3Channels) LOG(L"GUID_WICPixelFormat24bpp3Channels")
	if (wicPixelFormat == GUID_WICPixelFormat32bpp4Channels) LOG(L"GUID_WICPixelFormat32bpp4Channels")
	if (wicPixelFormat == GUID_WICPixelFormat40bpp5Channels) LOG(L"GUID_WICPixelFormat40bpp5Channels")
	if (wicPixelFormat == GUID_WICPixelFormat48bpp6Channels) LOG(L"GUID_WICPixelFormat48bpp6Channels")
	if (wicPixelFormat == GUID_WICPixelFormat56bpp7Channels) LOG(L"GUID_WICPixelFormat56bpp7Channels")
	if (wicPixelFormat == GUID_WICPixelFormat64bpp8Channels) LOG(L"GUID_WICPixelFormat64bpp8Channels")
	if (wicPixelFormat == GUID_WICPixelFormat48bpp3Channels) LOG(L"GUID_WICPixelFormat48bpp3Channels")
	if (wicPixelFormat == GUID_WICPixelFormat64bpp4Channels) LOG(L"GUID_WICPixelFormat64bpp4Channels")
	if (wicPixelFormat == GUID_WICPixelFormat80bpp5Channels) LOG(L"GUID_WICPixelFormat80bpp5Channels")
	if (wicPixelFormat == GUID_WICPixelFormat96bpp6Channels) LOG(L"GUID_WICPixelFormat96bpp6Channels")
	if (wicPixelFormat == GUID_WICPixelFormat112bpp7Channels) LOG(L"GUID_WICPixelFormat112bpp7Channels")
	if (wicPixelFormat == GUID_WICPixelFormat128bpp8Channels) LOG(L"GUID_WICPixelFormat128bpp8Channels")
	if (wicPixelFormat == GUID_WICPixelFormat40bppCMYKAlpha) LOG(L"GUID_WICPixelFormat40bppCMYKAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat80bppCMYKAlpha) LOG(L"GUID_WICPixelFormat80bppCMYKAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat32bpp3ChannelsAlpha) LOG(L"GUID_WICPixelFormat32bpp3ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat40bpp4ChannelsAlpha) LOG(L"GUID_WICPixelFormat40bpp4ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat48bpp5ChannelsAlpha) LOG(L"GUID_WICPixelFormat48bpp5ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat56bpp6ChannelsAlpha) LOG(L"GUID_WICPixelFormat56bpp6ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat64bpp7ChannelsAlpha) LOG(L"GUID_WICPixelFormat64bpp7ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat72bpp8ChannelsAlpha) LOG(L"GUID_WICPixelFormat72bpp8ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat64bpp3ChannelsAlpha) LOG(L"GUID_WICPixelFormat64bpp3ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat80bpp4ChannelsAlpha) LOG(L"GUID_WICPixelFormat80bpp4ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat96bpp5ChannelsAlpha) LOG(L"GUID_WICPixelFormat96bpp5ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat112bpp6ChannelsAlpha) LOG(L"GUID_WICPixelFormat112bpp6ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat128bpp7ChannelsAlpha) LOG(L"GUID_WICPixelFormat128bpp7ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat144bpp8ChannelsAlpha) LOG(L"GUID_WICPixelFormat144bpp8ChannelsAlpha")
	if (wicPixelFormat == GUID_WICPixelFormat8bppY) LOG(L"GUID_WICPixelFormat8bppY")
	if (wicPixelFormat == GUID_WICPixelFormat8bppCb) LOG(L"GUID_WICPixelFormat8bppCb")
	if (wicPixelFormat == GUID_WICPixelFormat8bppCr) LOG(L"GUID_WICPixelFormat8bppCr")
	if (wicPixelFormat == GUID_WICPixelFormat16bppCbCr) LOG(L"GUID_WICPixelFormat16bppCbCr")
	if (wicPixelFormat == GUID_WICPixelFormat16bppYQuantizedDctCoefficients) LOG(L"GUID_WICPixelFormat16bppYQuantizedDctCoefficients")
	if (wicPixelFormat == GUID_WICPixelFormat16bppCbQuantizedDctCoefficients) LOG(L"GUID_WICPixelFormat16bppCbQuantizedDctCoefficients")
	if (wicPixelFormat == GUID_WICPixelFormat16bppCrQuantizedDctCoefficients) LOG(L"GUID_WICPixelFormat16bppCrQuantizedDctCoefficients")
}